services:
  camunda:
    image: camunda/camunda-bpm-platform:7.20.0
    container_name: camunda
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://db:5432/camunda
      - DB_USERNAME=camunda
      - DB_PASSWORD=${POSTGRES_PASSWORD:-camunda}
      - JAVA_OPTS=-Xmx2g -Xms512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200
      - CAMUNDA_BPM_HISTORY_LEVEL=FULL
      - CAMUNDA_BPM_METRICS_FLAG=true
      - CAMUNDA_BPM_DB_SCHEMA_UPDATE=true
      - CAMUNDA_BPM_AUTHORIZATION_FLAG=true
      - CAMUNDA_BPM_WEBAPP_CSRF_COOKIE_SAMESITE=Strict
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/camunda/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      - db
    networks:
      - camunda-net
    volumes:
      - camunda_data:/camunda

  db:
    image: postgres:15-alpine
    container_name: camunda-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=camunda
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-camunda}
      - POSTGRES_DB=camunda
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U camunda"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - camunda-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: camunda-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - camunda-net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    container_name: camunda-kibana
    restart: unless-stopped
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - camunda-net

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: camunda-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - camunda-net

  grafana:
    image: grafana/grafana:10.1.0
    container_name: camunda-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - camunda-net

  nginx:
    image: nginx:1.25-alpine
    container_name: camunda-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - camunda
    networks:
      - camunda-net

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - camunda-net

networks:
  camunda-net:
    driver: bridge

volumes:
  pg_data:
  es_data:
  prometheus_data:
  grafana_data:
  camunda_data: