version: '3.8'
services:
  camunda:
    image: camunda/camunda-bpm-platform:7.19.0-tomcat
    container_name: camunda
    ports:
      - "8080:8080"
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://db:5432/camunda
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: camunda-db
    environment:
      - POSTGRES_USER=camunda
      - POSTGRES_PASSWORD=camunda
      - POSTGRES_DB=camunda
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  pg_data: