version: '3.8'

services:
  # Monitoring Stack (Production Grade)
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
    volumes:
      - influxdb_data:/var/lib/influxdb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - benchmark-network
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - benchmark-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # k6 Load Generator (Production Configuration)
  k6:
    image: grafana/k6:latest
    volumes:
      - ../../benchmarks/k6:/scripts
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=admin123
      - CAMUNDA_URL=http://host.docker.internal:8081
      - K6_ITERATIONS=1000
      - K6_VUS=50
      - K6_DURATION=30m
    depends_on:
      - influxdb
    command: run /scripts/loan-process-test.js
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - benchmark-network
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  # JMeter Load Generator (Production Configuration)
  jmeter:
    image: justb4/jmeter:latest
    volumes:
      - ../../benchmarks/jmeter:/jmeter
    environment:
      - HEAP=-Xms2g -Xmx4g
      - CAMUNDA_URL=http://host.docker.internal:8081
      - JMETER_THREADS=50
      - JMETER_RAMPUP=300
      - JMETER_DURATION=1800
      - INFLUXDB_URL=http://influxdb:8086/write?db=k6
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=admin123
    depends_on:
      - influxdb
    command: -n -t /jmeter/loan-process-test.jmx
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - benchmark-network
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

networks:
  benchmark-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

volumes:
  influxdb_data:
