version: '3.8'

services:
  # Monitoring Stack (Lightweight for Development)
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    volumes:
      - influxdb_data:/var/lib/influxdb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - benchmark-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - benchmark-network

  # k6 Load Generator (Development Configuration)
  k6:
    image: grafana/k6:latest
    volumes:
      - ../../benchmarks/k6:/scripts
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
      - CAMUNDA_URL=http://host.docker.internal:8080
      - K6_ITERATIONS=1000
      - K6_VUS=200
      - K6_DURATION=10m
    depends_on:
      - influxdb
    command: run /scripts/loan-process-test.js
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - benchmark-network

  # JMeter Load Generator (Development Configuration)
  jmeter:
    image: justb4/jmeter:latest
    volumes:
      - ../../benchmarks/jmeter:/jmeter
    environment:
      - HEAP=-Xms1g -Xmx2g
      - CAMUNDA_URL=http://host.docker.internal:8080
      - JMETER_THREADS=200
      - JMETER_RAMPUP=30
      - JMETER_DURATION=600
      - INFLUXDB_URL=http://influxdb:8086/write?db=k6
    depends_on:
      - influxdb
    command: -n -t /jmeter/loan-process-test.jmx
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - benchmark-network

networks:
  benchmark-network:
    driver: bridge

volumes:
  influxdb_data:
